# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonas Eltes
email: contact@jonaselt.es
description: 'Swedish New Media Artist & Designer.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonaselt.es" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jonaseltes
github_username:  jonaseltes
instagram_username: jonaselt.es
image_path: assets/media
js_path: assets/js
css_path: assets/css

# Scripts
head_scripts:
  - /assets/js/jquery.min.js
  - /assets/js/Tween.js
  - /assets/js/three.min.js
  - /assets/js/Projector.js
  - /assets/js/CanvasRenderer.js
  - /assets/js/OrbitControls.js
  - /assets/js/TrackballControls.js
  - /assets/js/OBJLoader.js
  - /assets/js/barba.min.js
  - /assets/js/perlin.js

body_scripts:
  - //code.jquery.com/jquery-3.2.1.min.js
  - //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  - //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  exhibitions:
    output: false


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
  - scope:
      path: "assets/media"
    values:
      image: true

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _projects/natura
  - log.md
